# Generated by Django 4.0.4 on 2022-06-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stamps', models.ManyToManyField(to='main_app.stamp')),
            ],
        ),
    ]
