# Generated by Django 4.0.4 on 2022-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='stamp',
            name='cost',
            field=models.IntegerField(default=1),
        ),
    ]
